# Generated by Django 4.0.1 on 2022-01-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='services',
            new_name='details',
        ),
    ]
